#!/usr/bin/env python3

from pathlib import Path

IMBALANCE = "Imbalance"

SEED = 1957 #2022
EVALUATION_SEQUENCE_SIZE = 144
TEST_SEQUENCE_SIZE       = 0

SIMPLE_STATE_EXTRACTION =1
MIN_STATE = 2
MAX_STATE = 10
CLASSIFICATION_FOR_STATE_EXTRACTION = 1
PCA_CLASSIFICATION_FOR_STATE_EXTRACTION = 1

EXOGENIOUS_CLASSIFICATION_ONLY = 1

PATH_ROOT_FOLDER = Path(Path(__file__).parent.absolute())
pass