# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import microservices_pb2 as microservices__pb2


class ObtainDataStub(object):
    """The read 'real demand','programmed'
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendData = channel.unary_unary(
                '/msrvcpred.ObtainData/SendData',
                request_serializer=microservices__pb2.DataRequest.SerializeToString,
                response_deserializer=microservices__pb2.DataReply.FromString,
                )
        self.SendStreamData = channel.unary_stream(
                '/msrvcpred.ObtainData/SendStreamData',
                request_serializer=microservices__pb2.TrainDataRequest.SerializeToString,
                response_deserializer=microservices__pb2.TrainDataReply.FromString,
                )


class ObtainDataServicer(object):
    """The read 'real demand','programmed'
    """

    def SendData(self, request, context):
        """Sends a data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendStreamData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObtainDataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendData': grpc.unary_unary_rpc_method_handler(
                    servicer.SendData,
                    request_deserializer=microservices__pb2.DataRequest.FromString,
                    response_serializer=microservices__pb2.DataReply.SerializeToString,
            ),
            'SendStreamData': grpc.unary_stream_rpc_method_handler(
                    servicer.SendStreamData,
                    request_deserializer=microservices__pb2.TrainDataRequest.FromString,
                    response_serializer=microservices__pb2.TrainDataReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'msrvcpred.ObtainData', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ObtainData(object):
    """The read 'real demand','programmed'
    """

    @staticmethod
    def SendData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/msrvcpred.ObtainData/SendData',
            microservices__pb2.DataRequest.SerializeToString,
            microservices__pb2.DataReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendStreamData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/msrvcpred.ObtainData/SendStreamData',
            microservices__pb2.TrainDataRequest.SerializeToString,
            microservices__pb2.TrainDataReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
