# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: microservices.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='microservices.proto',
  package='msrvcpred',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13microservices.proto\x12\tmsrvcpred\"Z\n\x10TrainDataRequest\x12\x10\n\x08\x63lientid\x18\x01 \x01(\x05\x12\x12\n\nstart_time\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\t\x12\x0e\n\x06region\x18\x04 \x01(\t\"\x8f\x01\n\x0eTrainDataReply\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x13\n\x0breal_demand\x18\x02 \x01(\x02\x12\x19\n\x11programmed_demand\x18\x03 \x01(\x02\x12\x17\n\x0f\x66orecast_demand\x18\x04 \x01(\x02\x12\x0e\n\x06status\x18\n \x01(\x05\x12\x11\n\tstatusmsg\x18\x0b \x01(\t\"/\n\x0b\x44\x61taRequest\x12\x10\n\x08\x63lientid\x18\x01 \x01(\x05\x12\x0e\n\x06region\x18\x04 \x01(\t\"\x8a\x01\n\tDataReply\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x13\n\x0breal_demand\x18\x02 \x01(\x02\x12\x19\n\x11programmed_demand\x18\x03 \x01(\x02\x12\x17\n\x0f\x66orecast_demand\x18\x04 \x01(\x02\x12\x0e\n\x06status\x18\n \x01(\x05\x12\x11\n\tstatusmsg\x18\x0b \x01(\t2\x96\x01\n\nObtainData\x12:\n\x08SendData\x12\x16.msrvcpred.DataRequest\x1a\x14.msrvcpred.DataReply\"\x00\x12L\n\x0eSendStreamData\x12\x1b.msrvcpred.TrainDataRequest\x1a\x19.msrvcpred.TrainDataReply\"\x00\x30\x01\x62\x06proto3'
)




_TRAINDATAREQUEST = _descriptor.Descriptor(
  name='TrainDataRequest',
  full_name='msrvcpred.TrainDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientid', full_name='msrvcpred.TrainDataRequest.clientid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='msrvcpred.TrainDataRequest.start_time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='msrvcpred.TrainDataRequest.end_time', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='region', full_name='msrvcpred.TrainDataRequest.region', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=124,
)


_TRAINDATAREPLY = _descriptor.Descriptor(
  name='TrainDataReply',
  full_name='msrvcpred.TrainDataReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='msrvcpred.TrainDataReply.timestamp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='real_demand', full_name='msrvcpred.TrainDataReply.real_demand', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='programmed_demand', full_name='msrvcpred.TrainDataReply.programmed_demand', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='forecast_demand', full_name='msrvcpred.TrainDataReply.forecast_demand', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='msrvcpred.TrainDataReply.status', index=4,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='statusmsg', full_name='msrvcpred.TrainDataReply.statusmsg', index=5,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=270,
)


_DATAREQUEST = _descriptor.Descriptor(
  name='DataRequest',
  full_name='msrvcpred.DataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientid', full_name='msrvcpred.DataRequest.clientid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='region', full_name='msrvcpred.DataRequest.region', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=319,
)


_DATAREPLY = _descriptor.Descriptor(
  name='DataReply',
  full_name='msrvcpred.DataReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='msrvcpred.DataReply.timestamp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='real_demand', full_name='msrvcpred.DataReply.real_demand', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='programmed_demand', full_name='msrvcpred.DataReply.programmed_demand', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='forecast_demand', full_name='msrvcpred.DataReply.forecast_demand', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='msrvcpred.DataReply.status', index=4,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='statusmsg', full_name='msrvcpred.DataReply.statusmsg', index=5,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=460,
)

DESCRIPTOR.message_types_by_name['TrainDataRequest'] = _TRAINDATAREQUEST
DESCRIPTOR.message_types_by_name['TrainDataReply'] = _TRAINDATAREPLY
DESCRIPTOR.message_types_by_name['DataRequest'] = _DATAREQUEST
DESCRIPTOR.message_types_by_name['DataReply'] = _DATAREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrainDataRequest = _reflection.GeneratedProtocolMessageType('TrainDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRAINDATAREQUEST,
  '__module__' : 'microservices_pb2'
  # @@protoc_insertion_point(class_scope:msrvcpred.TrainDataRequest)
  })
_sym_db.RegisterMessage(TrainDataRequest)

TrainDataReply = _reflection.GeneratedProtocolMessageType('TrainDataReply', (_message.Message,), {
  'DESCRIPTOR' : _TRAINDATAREPLY,
  '__module__' : 'microservices_pb2'
  # @@protoc_insertion_point(class_scope:msrvcpred.TrainDataReply)
  })
_sym_db.RegisterMessage(TrainDataReply)

DataRequest = _reflection.GeneratedProtocolMessageType('DataRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATAREQUEST,
  '__module__' : 'microservices_pb2'
  # @@protoc_insertion_point(class_scope:msrvcpred.DataRequest)
  })
_sym_db.RegisterMessage(DataRequest)

DataReply = _reflection.GeneratedProtocolMessageType('DataReply', (_message.Message,), {
  'DESCRIPTOR' : _DATAREPLY,
  '__module__' : 'microservices_pb2'
  # @@protoc_insertion_point(class_scope:msrvcpred.DataReply)
  })
_sym_db.RegisterMessage(DataReply)



_OBTAINDATA = _descriptor.ServiceDescriptor(
  name='ObtainData',
  full_name='msrvcpred.ObtainData',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=463,
  serialized_end=613,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendData',
    full_name='msrvcpred.ObtainData.SendData',
    index=0,
    containing_service=None,
    input_type=_DATAREQUEST,
    output_type=_DATAREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendStreamData',
    full_name='msrvcpred.ObtainData.SendStreamData',
    index=1,
    containing_service=None,
    input_type=_TRAINDATAREQUEST,
    output_type=_TRAINDATAREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OBTAINDATA)

DESCRIPTOR.services_by_name['ObtainData'] = _OBTAINDATA

# @@protoc_insertion_point(module_scope)
